/*
Copyright © 2020, "rupansh" <rupanshsekar@hotmail.com>

 This software is licensed under the terms of the GNU General Public
 License version 3, as published by the Free Software Foundation, and
 may be copied, distributed, and modified under those terms.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 Please maintain this if you use this script or any part of it
*/
use phf::phf_map;

#[allow(dead_code)]
pub static OFFSETS_NET: phf::Map<&'static str, u32> = phf_map!{
        "cs_gamerules_data" => 0x0,
        "m_ArmorValue" => 0xB368,
        "m_Collision" => 0x320,
        "m_CollisionGroup" => 0x474,
        "m_Local" => 0x2FBC,
        "m_MoveType" => 0x25C,
        "m_OriginalOwnerXuidHigh" => 0x31B4,
        "m_OriginalOwnerXuidLow" => 0x31B0,
        "m_SurvivalGameRuleDecisionTypes" => 0x1320,
        "m_SurvivalRules" => 0xCF8,
        "m_aimPunchAngle" => 0x302C,
        "m_aimPunchAngleVel" => 0x3038,
        "m_angEyeAnglesX" => 0xB36C,
        "m_angEyeAnglesY" => 0xB370,
        "m_bBombPlanted" => 0x99D,
        "m_bFreezePeriod" => 0x20,
        "m_bGunGameImmunity" => 0x3930,
        "m_bHasDefuser" => 0xB378,
        "m_bHasHelmet" => 0xB35C,
        "m_bInReload" => 0x3285,
        "m_bIsDefusing" => 0x391C,
        "m_bIsQueuedMatchmaking" => 0x74,
        "m_bIsScoped" => 0x3914,
        "m_bIsValveDS" => 0x75,
        "m_bSpotted" => 0x93D,
        "m_bSpottedByMask" => 0x980,
        "m_bStartedArming" => 0x33D0,
        "m_bUseCustomAutoExposureMax" => 0x9D9,
        "m_bUseCustomAutoExposureMin" => 0x9D8,
        "m_bUseCustomBloomScale" => 0x9DA,
        "m_clrRender" => 0x70,
        "m_dwBoneMatrix" => 0x26A8,
        "m_fAccuracyPenalty" => 0x3310,
        "m_fFlags" => 0x104,
        "m_flC4Blow" => 0x2990,
        "m_flCustomAutoExposureMax" => 0x9E0,
        "m_flCustomAutoExposureMin" => 0x9DC,
        "m_flCustomBloomScale" => 0x9E4,
        "m_flDefuseCountDown" => 0x29AC,
        "m_flDefuseLength" => 0x29A8,
        "m_flFallbackWear" => 0x31C0,
        "m_flFlashDuration" => 0xA410,
        "m_flFlashMaxAlpha" => 0xA40C,
        "m_flLastBoneSetupTime" => 0x2924,
        "m_flLowerBodyYawTarget" => 0x3A7C,
        "m_flNextAttack" => 0x2D70,
        "m_flNextPrimaryAttack" => 0x3218,
        "m_flSimulationTime" => 0x268,
        "m_flTimerLength" => 0x2994,
        "m_hActiveWeapon" => 0x2EF8,
        "m_hMyWeapons" => 0x2DF8,
        "m_hObserverTarget" => 0x3388,
        "m_hOwner" => 0x29CC,
        "m_hOwnerEntity" => 0x14C,
        "m_iAccountID" => 0x2FC8,
        "m_iClip1" => 0x3244,
        "m_iCompetitiveRanking" => 0x1A84,
        "m_iCompetitiveWins" => 0x1B88,
        "m_iCrosshairId" => 0xB3D4,
        "m_iEntityQuality" => 0x2FAC,
        "m_iFOV" => 0x31E4,
        "m_iFOVStart" => 0x31E8,
        "m_iGlowIndex" => 0xA428,
        "m_iHealth" => 0x100,
        "m_iItemDefinitionIndex" => 0x2FAA,
        "m_iItemIDHigh" => 0x2FC0,
        "m_iMostRecentModelBoneCounter" => 0x2690,
        "m_iObserverMode" => 0x3374,
        "m_iShotsFired" => 0xA380,
        "m_iState" => 0x3238,
        "m_iTeamNum" => 0xF4,
        "m_lifeState" => 0x25F,
        "m_nFallbackPaintKit" => 0x31B8,
        "m_nFallbackSeed" => 0x31BC,
        "m_nFallbackStatTrak" => 0x31C4,
        "m_nForceBone" => 0x268C,
        "m_nTickBase" => 0x342C,
        "m_rgflCoordinateFrame" => 0x444,
        "m_szCustomName" => 0x303C,
        "m_szLastPlaceName" => 0x35B0,
        "m_thirdPersonViewAngles" => 0x31D8,
        "m_vecOrigin" => 0x138,
        "m_vecVelocity" => 0x114,
        "m_vecViewOffset" => 0x108,
        "m_viewPunchAngle" => 0x3020,
};


pub static OFFSETS_SIG: phf::Map<&'static str, u32> = phf_map!{
        "anim_overlays" => 0x2980,
        "clientstate_choked_commands" => 0x4D28,
        "clientstate_delta_ticks" => 0x174,
        "clientstate_last_outgoing_command" => 0x4D24,
        "clientstate_net_channel" => 0x9C,
        "convar_name_hash_table" => 0x2F0F8,
        "dwClientState" => 0x588D9C,
        "dwClientState_GetLocalPlayer" => 0x180,
        "dwClientState_IsHLTV" => 0x4D40,
        "dwClientState_Map" => 0x28C,
        "dwClientState_MapDirectory" => 0x188,
        "dwClientState_MaxPlayer" => 0x388,
        "dwClientState_PlayerInfo" => 0x52B8,
        "dwClientState_State" => 0x108,
        "dwClientState_ViewAngles" => 0x4D88,
        "dwEntityList" => 0x4D3D5DC,
        "dwForceAttack" => 0x316EC9C,
        "dwForceAttack2" => 0x316ECA8,
        "dwForceBackward" => 0x316ECF0,
        "dwForceForward" => 0x316ECFC,
        "dwForceJump" => 0x51E0E00,
        "dwForceLeft" => 0x316EC78,
        "dwForceRight" => 0x316EC6C,
        "dwGameDir" => 0x6274F8,
        "dwGameRulesProxy" => 0x52540DC,
        "dwGetAllClasses" => 0xD4FC34,
        "dwGlobalVars" => 0x588AA0,
        "dwGlowObjectManager" => 0x527EEA0,
        "dwInput" => 0x5188778,
        "dwInterfaceLinkList" => 0x8F4DE4,
        "dwLocalPlayer" => 0xD29B1C,
        "dwMouseEnable" => 0xD2F6C0,
        "dwMouseEnablePtr" => 0xD2F690,
        "dwPlayerResource" => 0x316D01C,
        "dwRadarBase" => 0x517233C,
        "dwSensitivity" => 0xD2F55C,
        "dwSensitivityPtr" => 0xD2F530,
        "dwSetClanTag" => 0x89D60,
        "dwViewMatrix" => 0x4D2EFF4,
        "dwWeaponTable" => 0x518923C,
        "dwWeaponTableIndex" => 0x323C,
        "dwYawPtr" => 0xD2F320,
        "dwZoomSensitivityRatioPtr" => 0xD34540,
        "dwbSendPackets" => 0xD364A,
        "dwppDirect3DDevice9" => 0xA6030,
        "find_hud_element" => 0x29B6B5D0,
        "force_update_spectator_glow" => 0x397E52,
        "interface_engine_cvar" => 0x3E9EC,
        "is_c4_owner" => 0x3A4290,
        "m_bDormant" => 0xED,
        "m_flSpawnTime" => 0xA360,
        "m_pStudioHdr" => 0x294C,
        "m_pitchClassPtr" => 0x51725D8,
        "m_yawClassPtr" => 0xD2F320,
        "model_ambient_min" => 0x58BDBC,
        "set_abs_angles" => 0x1CEA80,
        "set_abs_origin" => 0x1CE8C0,
};