/*
Copyright © 2019, "rupansh" <rupanshsekar@hotmail.com>

 This software is licensed under the terms of the GNU General Public
 License version 3, as published by the Free Software Foundation, and
 may be copied, distributed, and modified under those terms.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 Please maintain this if you use this script or any part of it
*/

#[allow(non_snake_case)]
pub struct CSGOoffSetsNetval {
         pub cs_gamerules_data : u32,
         pub m_ArmorValue : u32,
         pub m_Collision : u32,
         pub m_CollisionGroup : u32,
         pub m_Local : u32,
         pub m_MoveType : u32,
         pub m_OriginalOwnerXuidHigh : u32,
         pub m_OriginalOwnerXuidLow : u32,
         pub m_SurvivalGameRuleDecisionTypes : u32,
         pub m_SurvivalRules : u32,
         pub m_aimPunchAngle : u32,
         pub m_aimPunchAngleVel : u32,
         pub m_angEyeAnglesX : u32,
         pub m_angEyeAnglesY : u32,
         pub m_bBombPlanted : u32,
         pub m_bFreezePeriod : u32,
         pub m_bGunGameImmunity : u32,
         pub m_bHasDefuser : u32,
         pub m_bHasHelmet : u32,
         pub m_bInReload : u32,
         pub m_bIsDefusing : u32,
         pub m_bIsQueuedMatchmaking : u32,
         pub m_bIsScoped : u32,
         pub m_bIsValveDS : u32,
         pub m_bSpotted : u32,
         pub m_bSpottedByMask : u32,
         pub m_bStartedArming : u32,
         pub m_bUseCustomAutoExposureMax : u32,
         pub m_bUseCustomAutoExposureMin : u32,
         pub m_bUseCustomBloomScale : u32,
         pub m_clrRender : u32,
         pub m_dwBoneMatrix : u32,
         pub m_fAccuracyPenalty : u32,
         pub m_fFlags : u32,
         pub m_flC4Blow : u32,
         pub m_flCustomAutoExposureMax : u32,
         pub m_flCustomAutoExposureMin : u32,
         pub m_flCustomBloomScale : u32,
         pub m_flDefuseCountDown : u32,
         pub m_flDefuseLength : u32,
         pub m_flFallbackWear : u32,
         pub m_flFlashDuration : u32,
         pub m_flFlashMaxAlpha : u32,
         pub m_flLastBoneSetupTime : u32,
         pub m_flLowerBodyYawTarget : u32,
         pub m_flNextAttack : u32,
         pub m_flNextPrimaryAttack : u32,
         pub m_flSimulationTime : u32,
         pub m_flTimerLength : u32,
         pub m_hActiveWeapon : u32,
         pub m_hMyWeapons : u32,
         pub m_hObserverTarget : u32,
         pub m_hOwner : u32,
         pub m_hOwnerEntity : u32,
         pub m_iAccountID : u32,
         pub m_iClip1 : u32,
         pub m_iCompetitiveRanking : u32,
         pub m_iCompetitiveWins : u32,
         pub m_iCrosshairId : u32,
         pub m_iEntityQuality : u32,
         pub m_iFOV : u32,
         pub m_iFOVStart : u32,
         pub m_iGlowIndex : u32,
         pub m_iHealth : u32,
         pub m_iItemDefinitionIndex : u32,
         pub m_iItemIDHigh : u32,
         pub m_iMostRecentModelBoneCounter : u32,
         pub m_iObserverMode : u32,
         pub m_iShotsFired : u32,
         pub m_iState : u32,
         pub m_iTeamNum : u32,
         pub m_lifeState : u32,
         pub m_nFallbackPaintKit : u32,
         pub m_nFallbackSeed : u32,
         pub m_nFallbackStatTrak : u32,
         pub m_nForceBone : u32,
         pub m_nTickBase : u32,
         pub m_rgflCoordinateFrame : u32,
         pub m_szCustomName : u32,
         pub m_szLastPlaceName : u32,
         pub m_thirdPersonViewAngles : u32,
         pub m_vecOrigin : u32,
         pub m_vecVelocity : u32,
         pub m_vecViewOffset : u32,
         pub m_viewPunchAngle : u32,
}

#[allow(non_snake_case)]
pub struct CSGOoffSetsSig {
         pub anim_overlays: u32,
         pub clientstate_choked_commands: u32,
         pub clientstate_delta_ticks: u32,
         pub clientstate_last_outgoing_command: u32,
         pub clientstate_net_channel: u32,
         pub convar_name_hash_table: u32,
         pub dwClientState: u32,
         pub dwClientState_GetLocalPlayer: u32,
         pub dwClientState_IsHLTV: u32,
         pub dwClientState_Map: u32,
         pub dwClientState_MapDirectory: u32,
         pub dwClientState_MaxPlayer: u32,
         pub dwClientState_PlayerInfo: u32,
         pub dwClientState_State: u32,
         pub dwClientState_ViewAngles: u32,
         pub dwEntityList: u32,
         pub dwForceAttack: u32,
         pub dwForceAttack2: u32,
         pub dwForceBackward: u32,
         pub dwForceForward: u32,
         pub dwForceJump: u32,
         pub dwForceLeft: u32,
         pub dwForceRight: u32,
         pub dwGameDir: u32,
         pub dwGameRulesProxy: u32,
         pub dwGetAllClasses: u32,
         pub dwGlobalVars: u32,
         pub dwGlowObjectManager: u32,
         pub dwInput: u32,
         pub dwInterfaceLinkList: u32,
         pub dwLocalPlayer: u32,
         pub dwMouseEnable: u32,
         pub dwMouseEnablePtr: u32,
         pub dwPlayerResource: u32,
         pub dwRadarBase: u32,
         pub dwSensitivity: u32,
         pub dwSensitivityPtr: u32,
         pub dwSetClanTag: u32,
         pub dwViewMatrix: u32,
         pub dwWeaponTable: u32,
         pub dwWeaponTableIndex: u32,
         pub dwYawPtr: u32,
         pub dwZoomSensitivityRatioPtr: u32,
         pub dwbSendPackets: u32,
         pub dwppDirect3DDevice9: u32,
         pub find_hud_element: u32,
         pub force_update_spectator_glow: u32,
         pub interface_engine_cvar: u32,
         pub is_c4_owner: u32,
         pub m_bDormant: u32,
         pub m_flSpawnTime: u32,
         pub m_pStudioHdr: u32,
         pub m_pitchClassPtr: u32,
         pub m_yawClassPtr: u32,
         pub model_ambient_min: u32,
         pub set_abs_angles: u32,
         pub set_abs_origin: u32,
}

pub const OFFSETS_NET: CSGOoffSetsNetval = CSGOoffSetsNetval {
    cs_gamerules_data: 0x0,
    m_ArmorValue: 0xB368,
    m_Collision: 0x320,
    m_CollisionGroup: 0x474,
    m_Local: 0x2FBC,
    m_MoveType: 0x25C,
    m_OriginalOwnerXuidHigh: 0x31B4,
    m_OriginalOwnerXuidLow: 0x31B0,
    m_SurvivalGameRuleDecisionTypes: 0x1320,
    m_SurvivalRules: 0xCF8,
    m_aimPunchAngle: 0x302C,
    m_aimPunchAngleVel: 0x3038,
    m_angEyeAnglesX: 0xB36C,
    m_angEyeAnglesY: 0xB370,
    m_bBombPlanted: 0x99D,
    m_bFreezePeriod: 0x20,
    m_bGunGameImmunity: 0x3930,
    m_bHasDefuser: 0xB378,
    m_bHasHelmet: 0xB35C,
    m_bInReload: 0x3285,
    m_bIsDefusing: 0x391C,
    m_bIsQueuedMatchmaking: 0x74,
    m_bIsScoped: 0x3914,
    m_bIsValveDS: 0x75,
    m_bSpotted: 0x93D,
    m_bSpottedByMask: 0x980,
    m_bStartedArming: 0x33D0,
    m_bUseCustomAutoExposureMax: 0x9D9,
    m_bUseCustomAutoExposureMin: 0x9D8,
    m_bUseCustomBloomScale: 0x9DA,
    m_clrRender: 0x70,
    m_dwBoneMatrix: 0x26A8,
    m_fAccuracyPenalty: 0x3310,
    m_fFlags: 0x104,
    m_flC4Blow: 0x2990,
    m_flCustomAutoExposureMax: 0x9E0,
    m_flCustomAutoExposureMin: 0x9DC,
    m_flCustomBloomScale: 0x9E4,
    m_flDefuseCountDown: 0x29AC,
    m_flDefuseLength: 0x29A8,
    m_flFallbackWear: 0x31C0,
    m_flFlashDuration: 0xA410,
    m_flFlashMaxAlpha: 0xA40C,
    m_flLastBoneSetupTime: 0x2924,
    m_flLowerBodyYawTarget: 0x3A7C,
    m_flNextAttack: 0x2D70,
    m_flNextPrimaryAttack: 0x3218,
    m_flSimulationTime: 0x268,
    m_flTimerLength: 0x2994,
    m_hActiveWeapon: 0x2EF8,
    m_hMyWeapons: 0x2DF8,
    m_hObserverTarget: 0x3388,
    m_hOwner: 0x29CC,
    m_hOwnerEntity: 0x14C,
    m_iAccountID: 0x2FC8,
    m_iClip1: 0x3244,
    m_iCompetitiveRanking: 0x1A84,
    m_iCompetitiveWins: 0x1B88,
    m_iCrosshairId: 0xB3D4,
    m_iEntityQuality: 0x2FAC,
    m_iFOV: 0x31E4,
    m_iFOVStart: 0x31E8,
    m_iGlowIndex: 0xA428,
    m_iHealth: 0x100,
    m_iItemDefinitionIndex: 0x2FAA,
    m_iItemIDHigh: 0x2FC0,
    m_iMostRecentModelBoneCounter: 0x2690,
    m_iObserverMode: 0x3374,
    m_iShotsFired: 0xA380,
    m_iState: 0x3238,
    m_iTeamNum: 0xF4,
    m_lifeState: 0x25F,
    m_nFallbackPaintKit: 0x31B8,
    m_nFallbackSeed: 0x31BC,
    m_nFallbackStatTrak: 0x31C4,
    m_nForceBone: 0x268C,
    m_nTickBase: 0x342C,
    m_rgflCoordinateFrame: 0x444,
    m_szCustomName: 0x303C,
    m_szLastPlaceName: 0x35B0,
    m_thirdPersonViewAngles: 0x31D8,
    m_vecOrigin: 0x138,
    m_vecVelocity: 0x114,
    m_vecViewOffset: 0x108,
    m_viewPunchAngle: 0x3020,
};

pub const OFFSETS_SIG: CSGOoffSetsSig = CSGOoffSetsSig {
    anim_overlays: 0x2980,
    clientstate_choked_commands: 0x4D28,
    clientstate_delta_ticks: 0x174,
    clientstate_last_outgoing_command: 0x4D24,
    clientstate_net_channel: 0x9C,
    convar_name_hash_table: 0x2F0F8,
    dwClientState: 0x588DA4,
    dwClientState_GetLocalPlayer: 0x180,
    dwClientState_IsHLTV: 0x4D40,
    dwClientState_Map: 0x28C,
    dwClientState_MapDirectory: 0x188,
    dwClientState_MaxPlayer: 0x388,
    dwClientState_PlayerInfo: 0x52B8,
    dwClientState_State: 0x108,
    dwClientState_ViewAngles: 0x4D88,
    dwEntityList: 0x4D3C5FC,
    dwForceAttack: 0x316DCBC,
    dwForceAttack2: 0x316DCC8,
    dwForceBackward: 0x316DD10,
    dwForceForward: 0x316DD1C,
    dwForceJump: 0x51DFE1C,
    dwForceLeft: 0x316DC98,
    dwForceRight: 0x316DC8C,
    dwGameDir: 0x6274F0,
    dwGameRulesProxy: 0x525310C,
    dwGetAllClasses: 0xD4EBC4,
    dwGlobalVars: 0x588AA8,
    dwGlowObjectManager: 0x527DEB0,
    dwInput: 0x5187798,
    dwInterfaceLinkList: 0x8F4A04,
    dwLocalPlayer: 0xD28AAC,
    dwMouseEnable: 0xD2E650,
    dwMouseEnablePtr: 0xD2E620,
    dwPlayerResource: 0x316C03C,
    dwRadarBase: 0x517135C,
    dwSensitivity: 0xD2E4EC,
    dwSensitivityPtr: 0xD2E4C0,
    dwSetClanTag: 0x89B20,
    dwViewMatrix: 0x4D2E014,
    dwWeaponTable: 0x518825C,
    dwWeaponTableIndex: 0x323C,
    dwYawPtr: 0xD2E2B0,
    dwZoomSensitivityRatioPtr: 0xD334D0,
    dwbSendPackets: 0xD333A,
    dwppDirect3DDevice9: 0xA6030,
    find_hud_element: 0x2DACB5D0,
    force_update_spectator_glow: 0x397E52,
    interface_engine_cvar: 0x3E9EC,
    is_c4_owner: 0x3A4290,
    m_bDormant: 0xED,
    m_flSpawnTime: 0xA360,
    m_pStudioHdr: 0x294C,
    m_pitchClassPtr: 0x51715F8,
    m_yawClassPtr: 0xD2E2B0,
    model_ambient_min: 0x58BDC4,
    set_abs_angles: 0x1CEA80,
    set_abs_origin: 0x1CE8C0,
};